defmodule CoconutWeb.CountryController do
  use CoconutWeb, :controller

  alias Coconut.Country

  @countries [
    %Country{name: "afghanistan", country_code: "AF"},
    %Country{name: "åland islands", country_code: "AX"},
    %Country{name: "albania", country_code: "AL"},
    %Country{name: "algeria", country_code: "DZ"},
    %Country{name: "american samoa", country_code: "AS"},
    %Country{name: "andorra", country_code: "AD"},
    %Country{name: "angola", country_code: "AO"},
    %Country{name: "anguilla", country_code: "AI"},
    %Country{name: "antarctica", country_code: "AQ"},
    %Country{name: "antigua and barbuda", country_code: "AG"},
    %Country{name: "argentina", country_code: "AR"},
    %Country{name: "armenia", country_code: "AM"},
    %Country{name: "aruba", country_code: "AW"},
    %Country{name: "australia", country_code: "AU"},
    %Country{name: "austria", country_code: "AT"},
    %Country{name: "azerbaijan", country_code: "AZ"},
    %Country{name: "bahamas", country_code: "BS"},
    %Country{name: "bahrain", country_code: "BH"},
    %Country{name: "bangladesh", country_code: "BD"},
    %Country{name: "barbados", country_code: "BB"},
    %Country{name: "belarus", country_code: "BY"},
    %Country{name: "belgium", country_code: "BE"},
    %Country{name: "belize", country_code: "BZ"},
    %Country{name: "benin", country_code: "BJ"},
    %Country{name: "bermuda", country_code: "BM"},
    %Country{name: "bhutan", country_code: "BT"},
    %Country{name: "bolivia", country_code: "BO"},
    %Country{name: "bosnia and herzegovina", country_code: "BA"},
    %Country{name: "botswana", country_code: "BW"},
    %Country{name: "bouvet island", country_code: "BV"},
    %Country{name: "brazil", country_code: "BR"},
    %Country{name: "british indian ocean territory", country_code: "IO"},
    %Country{name: "brunei darussalam", country_code: "BN"},
    %Country{name: "bulgaria", country_code: "BG"},
    %Country{name: "burkina faso", country_code: "BF"},
    %Country{name: "burundi", country_code: "BI"},
    %Country{name: "cambodia", country_code: "KH"},
    %Country{name: "cameroon", country_code: "CM"},
    %Country{name: "canada", country_code: "CA"},
    %Country{name: "cape verde", country_code: "CV"},
    %Country{name: "cayman islands", country_code: "KY"},
    %Country{name: "central african republic", country_code: "CF"},
    %Country{name: "chad", country_code: "TD"},
    %Country{name: "chile", country_code: "CL"},
    %Country{name: "china", country_code: "CN"},
    %Country{name: "christmas island", country_code: "CX"},
    %Country{name: "cocos (keeling) islands", country_code: "CC"},
    %Country{name: "colombia", country_code: "CO"},
    %Country{name: "comoros", country_code: "KM"},
    %Country{name: "congo", country_code: "CG"},
    %Country{name: "congo, the democratic republic of the", country_code: "CD"},
    %Country{name: "cook islands", country_code: "CK"},
    %Country{name: "costa rica", country_code: "CR"},
    %Country{name: "cote d'ivoire", country_code: "CI"},
    %Country{name: "croatia", country_code: "HR"},
    %Country{name: "cuba", country_code: "CU"},
    %Country{name: "cyprus", country_code: "CY"},
    %Country{name: "czech republic", country_code: "CZ"},
    %Country{name: "denmark", country_code: "DK"},
    %Country{name: "djibouti", country_code: "DJ"},
    %Country{name: "dominica", country_code: "DM"},
    %Country{name: "dominican republic", country_code: "DO"},
    %Country{name: "ecuador", country_code: "EC"},
    %Country{name: "egypt", country_code: "EG"},
    %Country{name: "el salvador", country_code: "SV"},
    %Country{name: "equatorial guinea", country_code: "GQ"},
    %Country{name: "eritrea", country_code: "ER"},
    %Country{name: "estonia", country_code: "EE"},
    %Country{name: "ethiopia", country_code: "ET"},
    %Country{name: "falkland islands (malvinas)", country_code: "FK"},
    %Country{name: "faroe islands", country_code: "FO"},
    %Country{name: "fiji", country_code: "FJ"},
    %Country{name: "finland", country_code: "FI"},
    %Country{name: "france", country_code: "FR"},
    %Country{name: "french guiana", country_code: "GF"},
    %Country{name: "french polynesia", country_code: "PF"},
    %Country{name: "french southern territories", country_code: "TF"},
    %Country{name: "gabon", country_code: "GA"},
    %Country{name: "gambia", country_code: "GM"},
    %Country{name: "georgia", country_code: "GE"},
    %Country{name: "germany", country_code: "DE"},
    %Country{name: "ghana", country_code: "GH"},
    %Country{name: "gibraltar", country_code: "GI"},
    %Country{name: "greece", country_code: "GR"},
    %Country{name: "greenland", country_code: "GL"},
    %Country{name: "grenada", country_code: "GD"},
    %Country{name: "guadeloupe", country_code: "GP"},
    %Country{name: "guam", country_code: "GU"},
    %Country{name: "guatemala", country_code: "GT"},
    %Country{name: "guernsey", country_code: "GG"},
    %Country{name: "guinea", country_code: "GN"},
    %Country{name: "guinea-bissau", country_code: "GW"},
    %Country{name: "guyana", country_code: "GY"},
    %Country{name: "haiti", country_code: "HT"},
    %Country{name: "heard island and mcdonald islands", country_code: "HM"},
    %Country{name: "holy see (vatican city state)", country_code: "VA"},
    %Country{name: "honduras", country_code: "HN"},
    %Country{name: "hong kong", country_code: "HK"},
    %Country{name: "hungary", country_code: "HU"},
    %Country{name: "iceland", country_code: "IS"},
    %Country{name: "india", country_code: "IN"},
    %Country{name: "indonesia", country_code: "ID"},
    %Country{name: "iran, islamic republic of", country_code: "IR"},
    %Country{name: "iraq", country_code: "IQ"},
    %Country{name: "ireland", country_code: "IE"},
    %Country{name: "isle of man", country_code: "IM"},
    %Country{name: "israel", country_code: "IL"},
    %Country{name: "italy", country_code: "IT"},
    %Country{name: "jamaica", country_code: "JM"},
    %Country{name: "japan", country_code: "JP"},
    %Country{name: "jersey", country_code: "JE"},
    %Country{name: "jordan", country_code: "JO"},
    %Country{name: "kazakhstan", country_code: "KZ"},
    %Country{name: "kenya", country_code: "KE"},
    %Country{name: "kiribati", country_code: "KI"},
    %Country{name: "korea, democratic people's republic of", country_code: "KP"},
    %Country{name: "korea, republic of", country_code: "KR"},
    %Country{name: "kuwait", country_code: "KW"},
    %Country{name: "kyrgyzstan", country_code: "KG"},
    %Country{name: "lao people's democratic republic", country_code: "LA"},
    %Country{name: "latvia", country_code: "LV"},
    %Country{name: "lebanon", country_code: "LB"},
    %Country{name: "lesotho", country_code: "LS"},
    %Country{name: "liberia", country_code: "LR"},
    %Country{name: "libyan arab jamahiriya", country_code: "LY"},
    %Country{name: "liechtenstein", country_code: "LI"},
    %Country{name: "lithuania", country_code: "LT"},
    %Country{name: "luxembourg", country_code: "LU"},
    %Country{name: "macao", country_code: "MO"},
    %Country{
      name: "Macedonia, The Former Yugoslav Republic of",
      country_code: "MK"
    },
    %Country{name: "madagascar", country_code: "MG"},
    %Country{name: "malawi", country_code: "MW"},
    %Country{name: "malaysia", country_code: "MY"},
    %Country{name: "maldives", country_code: "MV"},
    %Country{name: "mali", country_code: "ML"},
    %Country{name: "malta", country_code: "MT"},
    %Country{name: "marshall islands", country_code: "MH"},
    %Country{name: "martinique", country_code: "MQ"},
    %Country{name: "mauritania", country_code: "MR"},
    %Country{name: "mauritius", country_code: "MU"},
    %Country{name: "mayotte", country_code: "YT"},
    %Country{name: "mexico", country_code: "MX"},
    %Country{name: "micronesia, federated states of", country_code: "FM"},
    %Country{name: "moldova, republic of", country_code: "MD"},
    %Country{name: "monaco", country_code: "MC"},
    %Country{name: "mongolia", country_code: "MN"},
    %Country{name: "montserrat", country_code: "MS"},
    %Country{name: "morocco", country_code: "MA"},
    %Country{name: "mozambique", country_code: "MZ"},
    %Country{name: "myanmar", country_code: "MM"},
    %Country{name: "namibia", country_code: "NA"},
    %Country{name: "nauru", country_code: "NR"},
    %Country{name: "nepal", country_code: "NP"},
    %Country{name: "netherlands", country_code: "NL"},
    %Country{name: "netherlands antilles", country_code: "AN"},
    %Country{name: "new caledonia", country_code: "NC"},
    %Country{name: "new zealand", country_code: "NZ"},
    %Country{name: "nicaragua", country_code: "NI"},
    %Country{name: "niger", country_code: "NE"},
    %Country{name: "nigeria", country_code: "NG"},
    %Country{name: "niue", country_code: "NU"},
    %Country{name: "norfolk island", country_code: "NF"},
    %Country{name: "northern mariana islands", country_code: "MP"},
    %Country{name: "norway", country_code: "NO"},
    %Country{name: "oman", country_code: "OM"},
    %Country{name: "pakistan", country_code: "PK"},
    %Country{name: "palau", country_code: "PW"},
    %Country{name: "palestinian territory, occupied", country_code: "PS"},
    %Country{name: "panama", country_code: "PA"},
    %Country{name: "papua new guinea", country_code: "PG"},
    %Country{name: "paraguay", country_code: "PY"},
    %Country{name: "peru", country_code: "PE"},
    %Country{name: "philippines", country_code: "PH"},
    %Country{name: "pitcairn", country_code: "PN"},
    %Country{name: "poland", country_code: "PL"},
    %Country{name: "portugal", country_code: "PT"},
    %Country{name: "puerto rico", country_code: "PR"},
    %Country{name: "qatar", country_code: "QA"},
    %Country{name: "reunion", country_code: "RE"},
    %Country{name: "romania", country_code: "RO"},
    %Country{name: "russian federation", country_code: "RU"},
    %Country{name: "rwanda", country_code: "RW"},
    %Country{name: "saint helena", country_code: "SH"},
    %Country{name: "saint kitts and nevis", country_code: "KN"},
    %Country{name: "saint lucia", country_code: "LC"},
    %Country{name: "saint pierre and miquelon", country_code: "PM"},
    %Country{name: "saint vincent and the grenadines", country_code: "VC"},
    %Country{name: "samoa", country_code: "WS"},
    %Country{name: "san marino", country_code: "SM"},
    %Country{name: "sao tome and principe", country_code: "ST"},
    %Country{name: "saudi arabia", country_code: "SA"},
    %Country{name: "senegal", country_code: "SN"},
    %Country{name: "serbia and montenegro", country_code: "CS"},
    %Country{name: "seychelles", country_code: "SC"},
    %Country{name: "sierra leone", country_code: "SL"},
    %Country{name: "singapore", country_code: "SG"},
    %Country{name: "slovakia", country_code: "SK"},
    %Country{name: "slovenia", country_code: "SI"},
    %Country{name: "solomon islands", country_code: "SB"},
    %Country{name: "somalia", country_code: "SO"},
    %Country{name: "south africa", country_code: "ZA"},
    %Country{name: "south georgia and the south sandwich islands", country_code: "GS"},
    %Country{name: "spain", country_code: "ES"},
    %Country{name: "sri lanka", country_code: "LK"},
    %Country{name: "sudan", country_code: "SD"},
    %Country{name: "suriname", country_code: "SR"},
    %Country{name: "svalbard and jan mayen", country_code: "SJ"},
    %Country{name: "swaziland", country_code: "SZ"},
    %Country{name: "sweden", country_code: "SE"},
    %Country{name: "switzerland", country_code: "CH"},
    %Country{name: "syrian arab republic", country_code: "SY"},
    %Country{name: "taiwan, province of china", country_code: "TW"},
    %Country{name: "tajikistan", country_code: "TJ"},
    %Country{name: "tanzania, united republic of", country_code: "TZ"},
    %Country{name: "thailand", country_code: "TH"},
    %Country{name: "timor-leste", country_code: "TL"},
    %Country{name: "togo", country_code: "TG"},
    %Country{name: "tokelau", country_code: "TK"},
    %Country{name: "tonga", country_code: "TO"},
    %Country{name: "trinidad and tobago", country_code: "TT"},
    %Country{name: "tunisia", country_code: "TN"},
    %Country{name: "turkey", country_code: "TR"},
    %Country{name: "turkmenistan", country_code: "TM"},
    %Country{name: "turks and caicos islands", country_code: "TC"},
    %Country{name: "tuvalu", country_code: "TV"},
    %Country{name: "uganda", country_code: "UG"},
    %Country{name: "ukraine", country_code: "UA"},
    %Country{name: "united arab emirates", country_code: "AE"},
    %Country{name: "united kingdom", country_code: "GB"},
    %Country{name: "united states", country_code: "US"},
    %Country{name: "usa", country_code: "US"},
    %Country{name: "united states minor outlying islands", country_code: "UM"},
    %Country{name: "uruguay", country_code: "UY"},
    %Country{name: "uzbekistan", country_code: "UZ"},
    %Country{name: "vanuatu", country_code: "VU"},
    %Country{name: "venezuela", country_code: "VE"},
    %Country{name: "viet nam", country_code: "VN"},
    %Country{name: "virgin islands, british", country_code: "VG"},
    %Country{name: "virgin islands, u.s.", country_code: "VI"},
    %Country{name: "wallis and futuna", country_code: "WF"},
    %Country{name: "western sahara", country_code: "EH"},
    %Country{name: "yemen", country_code: "YE"},
    %Country{name: "zambia", country_code: "ZM"},
    %Country{name: "zimbabwe", country_code: "ZW"}
  ]

  def index(conn, _params) do
    response = %{
      status: "ok",
      data: @countries
    }

    render(conn, "index.json", response: response)
  end
end
